version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "leroy-test-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-g5mp6ivkxwrh"
s3_prefix = "leroy-test-sam"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
